version: '3.8'
services:
  postgresql-b:
    image: postgres:14.1-alpine
    restart: always
    command:  
      - "postgres"
      - "-c"
      - "max_prepared_transactions=100"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      
  postgresql-b1:
    image: postgres:14.1-alpine
    restart: always
    command:  
      - "postgres"
      - "-c"
      - "max_prepared_transactions=100"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5433:5432'
    volumes: 
      - db2:/var/lib/postgresql/data

  postgresql-b2:
    image: postgres:14.1-alpine
    restart: always
    command:  
      - "postgres"
      - "-c"
      - "max_prepared_transactions=100"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes: 
      - db3:/var/lib/postgresql/data
      
volumes:
  db:
    driver: local
  db2:
    driver: local
  db3:
    driver: local